config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'

  resources :jewelries, except: :destroy

  get 'jewelries/sell/:id' => 'jewelries#sell', as: :jewelry_sell
  get 'jewelries/sellable/:id' => 'jewelries#mark_for_sale', as: :jewelry_sellable

  resources :users, only: :show

end

app/models/jewelry.rb
class Jewelry < ActiveRecord::Base
  def sell(buyer)
    if !self.sellable || (self.user_id == buyer.id)
      return false
    else
      self.update({:user_id => buyer.id, :sellable => false})
      return true
    end
  end

  def mark_for_sale
    self.update({:sellable => true}) if !self.sellable
  end

  def verify_input
    msg = nil
    if self.jewelry_type == nil
      msg = "You must specify a valid jewelry type."
    elsif self.materials_cost.to_i <= 0
      msg = "You must specify a valid materials cost."
    elsif self.hours_worked.to_i <= 0
      msg = "You must specify a valid number of hours worked."
    end
    return msg
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jewelries

  validates :username, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\z/, message: "username can only contain letters and numbers"}
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:email, :username]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
end

app/controllers/jewelries_controller.rb
class JewelriesController < ApplicationController

  def mark_for_sale
    @to_mark = Jewelry.find_by_id(params['id'])
    if (current_user.id != @to_mark.user_id)
      flash[:alert] = "You cannot sell that which you do not own!"
      redirect_to root_path
    else
      @to_mark.mark_for_sale
      flash[:notice] = "It is now ready for sale."
      redirect_to user_path(current_user)
    end
  end

  def sell
    @to_sell = Jewelry.find_by_id(params['id'])
    if @to_sell.sell(current_user)
      flash[:notice] = "You bought it."
      redirect_to user_path(current_user)
    else
      flash[:alert] = "You didn't buy it, something went wrong."
      redirect_to jewelries_path
    end
  end

  def index
    @jewelries = Jewelry.where({:sellable => true})
  end

  def new
    @jewelry = Jewelry.new
  end

  def create
    jewelry_params = params.require(:jewelry).permit(:jewelry_type, :materials_cost, :hours_worked, :user_id)
    @jewelry = current_user.jewelries.new(jewelry_params)
    msg = @jewelry.verify_input
    if (!msg && @jewelry.save)
      flash[:notice] = "Your jewelry has been created."
      redirect_to user_path(current_user)
    else
      flash[:alert] = "Your jewelry has not been created."
      flash[:alert] += " " + msg if msg
      redirect_to new_jewelry_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by_id(params[:id])
    @jewelries = @user.jewelries.order(:jewelry_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
-if current_user
  %h2= "Welcome back to Jewelretsy, #{current_user.username}! Please use the links above to make, view, or buy jewelry."
-else
  %h2= "Welcome to Jewelretsy! Please sign in above, or sign up if it is your first time here."

app/views/jewelries/index.html.haml
-if @jewelries.empty?
  %h2= "No one has any jewelry for sale! Try making some of your own, then make it sellable."
-else
  %h2= "Here are the current jewelries for sale:"

  %table
    %thead
      %tr
        %th Jewelry type
        %th Materials cost
        %th Hours worked
        %th Asking price
        %th Owner
        %th Buy?
    %tbody
      -@jewelries.each do |j|
        %tr
          %th= [nil, "Necklace", "Bracelet", "Earrings"][j.jewelry_type]
          %th= sprintf("%0.02f", j.materials_cost)
          %th= sprintf("%0.02f", j.hours_worked)
          %th= sprintf("%0.02f", j.materials_cost + (j.hours_worked * 10))
          %th= User.find_by_id(j.user_id).username
          -if j.user_id != current_user.id
            %th= link_to "Buy", jewelry_sell_path(j.id)
          -else
            %th

app/views/jewelries/new.html.haml
%h2 Add jewelry
= simple_form_for(@jewelry) do |f|
  = f.input :jewelry_type, as: :select, collection: [['Necklace', 1], ['Bracelet', 2], ['Earrings', 3]]
  = f.input :materials_cost, as: :integer
  = f.input :hours_worked, as: :integer
  = f.input :user_id, as: :hidden, value: current_user.id
  = f.button :submit, "Add jewelry", method: "post"

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Rails Jewelry app"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    .small-3.columns
      %h1
    .small-5.columns#middle
      %h1#header-logo= image_tag "jewelretsy.png"
      - if notice
        .alert_box.success= notice
      - if alert
        .alert_box.alert= alert
      %ul#navigation
        - if user_signed_in?
          %li= link_to 'Sign out', destroy_user_session_path, method: 'delete'
          %li= link_to 'Jewelries', jewelries_path
          %li= link_to 'Add jewelry', new_jewelry_path
          %li= link_to 'Your jewelry', user_path(current_user)
        - else
          %li= link_to 'Sign in', new_user_session_path

      = yield
    .small-3.columns
      %h1
    = javascript_include_tag "application"

app/views/users/show.html.haml
%h1= "Hello " + @user.username + "!"

-if @jewelries.empty?
  %h2= "You don't have any jewelry! Why don't you use the buttons above to make some, or buy some from someone else?"
-else
  %h2= "Here are your jewelries:"

  %table
    %thead
      %tr
        %th Jewelry type
        %th Materials cost
        %th Hours worked
        %th Asking price
        %th Sellable?
    %tbody
      -@jewelries.each do |j|
        %tr
          %th= [nil, "Necklace", "Bracelet", "Earrings"][j.jewelry_type]
          %th= sprintf("%0.02f", j.materials_cost)
          %th= sprintf("%0.02f", j.hours_worked)
          %th= sprintf("%0.02f", j.materials_cost + (j.hours_worked * 10))
          -if j.sellable
            %th= "Yes"
          -else
            %th=  link_to "Make sellable",  jewelry_sellable_path(j.id)